# Pre-shared key for the hub <-> on-premises IPsec tunnel. 
# Generated by the provider `random` rather than written 
# by hand in plain text. The lab is destroyed nightly, so
# the key is regenerated on every rebuild.
resource "random_password" "ipsec_psk" {
  length  = 48
  special = false
}